name: Daily NEET PG Shorts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # runs daily at 5:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --force-reinstall moviepy pillow google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
          pip show moviepy
          python -c "import moviepy.editor as m; print('✅ MoviePy installed OK:', m.__file__)"

      - name: Run script
        run: python main.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
